### ISSUE TITLE
Pip version error after update to 2022.05

### ISSUE THREAD

**Issue by seandboss** [sam43434/remootio#1]
Unable to install package aioremootio==1.0.0a14: ERROR: Cannot install aioremootio==1.0.0a14 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by seandboss** [comment]
After the update to 2022.05, Remootio HACS integration won't load, can't be removed and complains of missing dependencies

**Comment by peaceduck** [comment]
I can verify the same problems after updating to 2022.05

**Comment by peaceduck** [comment]
It is a problem with the aioremootio-library. It has a dependency to an old version of voluptuous, which seems to cause some problems.
I have made a workaround-hack, described here: 
[https://community.home-assistant.io/t/remootio-garage-door-automation-new-product/110559/55]
It works for me, but hopefully it will get officially fixed soon.

**Comment by seandboss** [comment]
> It is a problem with the aioremootio-library. It has a dependency to an old version of voluptuous, which seems to cause some problems.
> I have made a workaround-hack, described here: 
> [https://community.home-assistant.io/t/remootio-garage-door-automation-new-product/110559/55]
> It works for me, but hopefully it will get officially fixed soon.
> 

Thanks, that works for me too
