### ISSUE TITLE
Errors after upgrading to 2023.7.3

### ISSUE THREAD

**Issue by nivek1612** [sam43434/remootio#13]
Home Assistant Core
Setup failed for custom integration remootio: Requirements for remootio not found: ['aioremootio @ git+https://github.com/sam43434/aioremootio.git'].
13:54:12 – (ERROR) setup.py
Unable to install package aioremootio @ git+https://github.com/sam43434/aioremootio.git: ERROR: Cannot install aioremootio==1.0.0.dev0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
13:54:12 – (ERROR) util/package.py - message first occurred at 13:53:38 and shows up 3 times

**Comment by yarafie** [comment]
Already reporrted.

Check the link below for a temporary (A little involved) until @sam43434 applies the fix.

https://github.com/sam43434/remootio/issues/12

**Comment by nivek1612** [comment]
Thanks, I missed that. Already have my own fork (previous issue) so quick change for me.
