### ISSUE TITLE
:0:0 Script error.  / 2023.8.2

### ISSUE THREAD

**Issue by MrJoshFisher** [sam43434/remootio#15]
Hello, 

Facing an issue with the integration getting the following error:

```
Logger: frontend.js.latest.202308020
Source: components/system_log/__init__.py:270 
First occurred: 19:58:21 (1 occurrences) 
Last logged: 19:58:21

:0:0 Script error.
```

Im running the latest version as of today: 2023.8.2

My steps:

1. Added the custom repo to HACS
2. Downloaded the repo through hacs
3. logged in via terminal and modified the const.py file adding my serial number, api key and api secret key, 
4. wasn't sure about the domain in the const.py so left as is.
5. Followed the steps that @yarafie mentioned in [Remootio after latest update on HA (22-07-23)](https://github.com/sam43434/remootio/issues/12#issuecomment-1646500225)
6. Forked the repo
7. Updated requirments
8. change the username in the forked repo to my own
9. restarted HA
10. Went to integrations added remootio (just spins when trying to load the wizard)
11. Checked the logs see error above.

If I've missed a step let me know as I'm fairly new to this.

Cheers

Josh

**Comment by MrJoshFisher** [comment]
After updating to 2023.8.3 nothing in the logs but the wizard just spins

**Comment by yarafie** [comment]
I just updated to 8.3 and all is working.

Not sure why your editing const.py directly shouldnt have to.

I suggest you start clean

1. Remove the remootio integration first then redownload remootio through HACS
2. Do the aiohttp edits I mentioned to remootio (I assume you already have your own github/aiohttp version)
3. restart HA
4. Add remootio as an integration, it will ask you for remootio keys etc.

**Comment by MrJoshFisher** [comment]
Whoop that worked! cheers
