### ISSUE TITLE
How to use the open/close

### ISSUE THREAD

**Issue by netnutmike** [sam43434/remootio#2]
I am not sure if this is an issue or user error.

I installed the repo and configured both of my Remootio devices.  I can see the status but do not see how to actually open or close the doors.  I see the code for opening and closing but cannot figure out how to call them.  There is no button defined and there does not seem to be a service defined to call.

**Comment by peaceduck** [comment]
This integration uses the home assistant entity class "cover". You can find more info here
[https://www.home-assistant.io/integrations/cover/](url)
Depending on the card you use, you should be able to see an up-arrow and a down-arrow. Click those for open or close.
If you dont see them, you can probably click on your status icon and get them there. I suggest you find some good UI-card to display them. You could also use automation and services to open and close. The most interesting services are 
`cover.open_cover`
`cover.close_cover`
`cover.cover_toggle`
