### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by Begie1605** [sam43434/remootio#6]
Could someone tell me where i have to put ip/secret etc...i don't see any config possibility on the integration in hacs.
I suppose i need to enter it in a file, but what file?

**Comment by yarafie** [comment]
> Could someone tell me where i have to put ip/secret etc...i don't see any config possibility on the integration in hacs. I suppose i need to enter it in a file, but what file?

You add it as an integration a GUI Will appear and then fill in the IP Address and the Auth and Secret Keys you get from the actual remootio app.

**Comment by Begie1605** [comment]
> 

Then somewhere i have done something wrong...
I added it via hacs en custom repository...restarted and it show now as a HACS integration......but i did not see a gui ...so am i still missing something (sorry for the stupid questions but i'm rather new to HA.)

**Comment by yarafie** [comment]
No problem.

So you see it in Homeassistant under hacs thats good step 1 done :)

What you need to do now is go to

Settings
Devices and Services
+ ADD INTEGRATION

search for remootio add it and the GUI I mentioned will appear

**Comment by Begie1605** [comment]
Thnx yarafie....

Offcourse ....this is the step i always forget when adding integrations......I will make a BIG note to do that last step also with hacs integrations

PS. It is connected and everything now....so when i'm home i will test it.....and then all my things that have been on smartthings before are now on HA........and offcourse many more now...

**Comment by yarafie** [comment]
Your most welcome.

Welcome to the world of HA.
