### ISSUE TITLE
remootio needs update in preperation for 2023.3

### ISSUE THREAD

**Issue by yarafie** [sam43434/remootio#7]
@sam43434 remootio needs update in preperation for 2023.3 see warning below from latest version

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 5:23:16 PM (1 occurrences)
Last logged: 5:23:16 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for remootio using this method at custom_components/remootio/__init__.py, line 45: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by nivek1612** [comment]
I was just about to raise this as well. thanks @yarafie

**Comment by yarafie** [comment]
> I was just about to raise this as well. thanks @yarafie

No prob I fixed it in my own fork you can see what I did in the pull request simple change

**Comment by sam43434** [comment]
merged

**Comment by yarafie** [comment]
Thanks for addressing it issue closed

**Comment by jwinston100** [comment]
Sorry, but I'm not sure if the issue was fixed. The Remootio integration failed when I upgraded to 2023.3, so I had to downgrade back to 2022.2.5.

**Comment by yarafie** [comment]
> Sorry, but I'm not sure if the issue was fixed. The Remootio integration failed when I upgraded to 2023.3, so I had to downgrade back to 2022.2.5.

I beleive it was fixed did you re-download it?
I havent yet updated HA to 2023.3 yet so cant confirm

**Comment by jwinston100** [comment]
I didn't redownload the Remootio integration before updating HA to 2022.3, but HACS didn't indicate there was an update available. I have version 57e0920 which seems to be the latest version in the repository. I'm sorry that I can't provide the specific error I had. Unfortunately I didn't think to note it before downgrading HA back to 2022.2.5.

**Comment by yarafie** [comment]
> I didn't redownload the Remootio integration before updating HA to 2022.3, but HACS didn't indicate there was an update available. I have version [57e0920](https://github.com/sam43434/remootio/commit/57e092086afd65245be0c83e156f675fd21714c3) which seems to be the latest version in the repository. I'm sorry that I can't provide the specific error I had. Unfortunately I didn't think to note it before downgrading HA back to 2022.2.5.

Try redownloading it in HACS. I don't plan to upgrade yet  to HA 2023.3 but will do in next few days and will let you know

**Comment by yarafie** [comment]
I just updated and new error

/usr/local/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (None)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(

2023-03-02 16:58:32.346 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package aioremootio==1.0.0a17: ERROR: Cannot install aioremootio==1.0.0a17 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
2023-03-02 16:58:38.500 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package aioremootio==1.0.0a17: ERROR: Cannot install aioremootio==1.0.0a17 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip

**Comment by jwinston100** [comment]
Yes, I upgraded again after re-downloading the integration, and same error as you. I tried re-downloading the integration and received this error:

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 8:05:04 AM (3 occurrences)
Last logged: 8:05:28 AM

Unable to install package aioremootio==1.0.0a17: ERROR: Cannot install aioremootio==1.0.0a17 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by yarafie** [comment]
> Yes, I upgraded again after re-downloading the integration, and same error as you. I tried re-downloading the integration and received this error:
> 
> Logger: homeassistant.util.package Source: util/package.py:107 First occurred: 8:05:04 AM (3 occurrences) Last logged: 8:05:28 AM
> 
> Unable to install package aioremootio==1.0.0a17: ERROR: Cannot install aioremootio==1.0.0a17 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

Yup it has to do with a dependency of remootio  using external library/api called aioremootio which needs to be updated. This happened once before and HA Devs reverted something in HA which fixed it not sure if same case here will be done.

**Comment by yarafie** [comment]
Ok Confirmed aioremootio needs to be updated.

I forked the  aioremootio repo and updated requirements.txt for the two dependencies below to
aiohttp==3.8.4
pycryptodome==3.17

================================================
aioremootio repo https://github.com/ivgg-me/aioremootio
================================================

I then in remootio hacs changed the requirements line in manifest.json to point to my forked aioremootio fork
 "requirements": ["aioremootio @ git+https://github.com/<github userid>/aioremootio.git"],

restarted HA and its working

**Comment by jwinston100** [comment]
Thank you for your help with this. I tried adding your new repo as a custom repository in HACS, but received the error

<Integration ivgg-me/aioremootio> Repository structure for 1.0.0.alpha17 is not compliant

**Comment by yarafie** [comment]
> Thank you for your help with this. I tried adding your new repo as a custom repository in HACS, but received the error
> 
> <Integration ivgg-me/aioremootio> Repository structure for 1.0.0.alpha17 is not compliant

Sorry thats not going to work. The repo your trying to add which I mentioned above is not the HACS remootio its the library/api that remootio uses. If your not comfortable manually editing files then you will have to wait for the official fixes. Ive done a pull request to dev of aioremootio but don't know if he will fix it.

**Comment by jwinston100** [comment]
I'm OK with editing files, but how do I get that forked API to my HA or edit the requirements.txt document? I cannot find that document on my HA anywhere. Is there a file on the HACS Remootio integration to edit to point to your API fork? Thanks.

**Comment by yarafie** [comment]
> I'm OK with editing files, but how do I get that forked API to my HA or edit the requirements.txt document? I cannot find that document on my HA anywhere. Is there a file on the HACS Remootio integration to edit to point to your API fork? Thanks.

Ok.
I prefer you be in complete control so if i break something on my side it doesnt affect you so here is a step by step. I am going to assume you know how to use github and you know the location of remootio HACS Files

1. Go to github and fork the aioremootio repo
https://github.com/ivgg-me/aioremootio

2. edit the requirements.txt file in your own aioremootio fork and change to below versions
aiohttp==3.8.4
pycryptodome==3.17
async-class==0.5.0
voluptuous==0.13.1

3. Go to your HA /config/custom_components/remootio/

4. edit manifest.json file and change the line with requirements to look like the below
"requirements": ["aioremootio @ git+https://github.com/GITHUBUSERID<github userid>/aioremootio.git"],
but change GITHUBUSERID to yours

Don't redownload remootio HACS Otherwise you will overwrite your changes done in step 4

Restart HA and you should be good to go.

**Comment by jwinston100** [comment]
Thank you, yarafie!

**Comment by nivek1612** [comment]
@sam43434 will you be making the same updates. I'd rather not mess with Github etc

**Comment by nivek1612** [comment]
Ok I'm going to take a pop at this 

@yarafie should there really be two '/' after the GITHUBUSERID in step 4 above

**Comment by yarafie** [comment]
> Ok I'm going to take a pop at this
> 
> @yarafie should there really be two '/' after the GITHUBUSERID in step 4 above

Corrected github added an extra / :)

Anyhow, no need to go through it, DEV fixed it from his end.

**Comment by nivek1612** [comment]
I had a go anyway. Never know when I might really need to do it.

Worked well
